
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**This is the main parent form
     *  all the other windows will be a child product of this object
     *  all the variables and functions and classes will be present here.
     *  To the other coders(if any) - Please follow the proper indentation and keep proper 
     *  spacing in between functions. More spaces More clean project More easy for me to understand
     *  - @author Pavitra 
    */
public class frameMain extends javax.swing.JFrame {

    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginSF = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usrTXT = new javax.swing.JTextField();
        pwdTXT = new javax.swing.JPasswordField();
        cmdLogin = new javax.swing.JButton();
        intSF = new javax.swing.JFrame();
        cmdSTDINFO = new javax.swing.JButton();
        cmdBUSINFO = new javax.swing.JButton();
        cmdROTINFO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        loggMenu = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        stdInfoSF = new javax.swing.JFrame();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        stdInfoSearch = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        busInfoSF = new javax.swing.JFrame();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        busInfoSearch = new javax.swing.JButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        rInfoSF = new javax.swing.JFrame();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        rInfoSearch = new javax.swing.JButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        loginSF.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginSF.setTitle("Login ");
        loginSF.setMinimumSize(new java.awt.Dimension(328, 132));
        loginSF.setName("frame1login"); // NOI18N
        loginSF.setResizable(false);
        loginSF.setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        cmdLogin.setText("Login");
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginSFLayout = new javax.swing.GroupLayout(loginSF.getContentPane());
        loginSF.getContentPane().setLayout(loginSFLayout);
        loginSFLayout.setHorizontalGroup(
            loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSFLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginSFLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usrTXT)
                            .addComponent(pwdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmdLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        loginSFLayout.setVerticalGroup(
            loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginSFLayout.createSequentialGroup()
                .addGroup(loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginSFLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(usrTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdLogin)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        intSF.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        intSF.setTitle("Little World School Bus Management");
        intSF.setMinimumSize(new java.awt.Dimension(658, 352));
        intSF.setResizable(false);

        cmdSTDINFO.setText("Student Info");
        cmdSTDINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSTDINFOActionPerformed(evt);
            }
        });

        cmdBUSINFO.setText("Bus Info");
        cmdBUSINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBUSINFOActionPerformed(evt);
            }
        });

        cmdROTINFO.setText("Route Info");
        cmdROTINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdROTINFOActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new DefaultTableModel());
        jScrollPane2.setViewportView(jTable1);

        jMenu2.setText("Info");

        loggMenu.setText("Logged in as - TestUser");
        loggMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggMenuActionPerformed(evt);
            }
        });
        jMenu2.add(loggMenu);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Logout/Exit");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Edit");

        jMenu5.setText("Students");

        jMenuItem1.setText("Add Student");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Delete Student");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Edit Student");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenu4.add(jMenu5);

        jMenu6.setText("Buses");

        jMenuItem4.setText("Add bus");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Remove bus");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuItem6.setText("Edit bus info");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenu4.add(jMenu6);

        jMenu7.setText("Routes");

        jMenuItem7.setText("New Route");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("Delete Route");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Edit Route info");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenu4.add(jMenu7);

        jMenuBar1.add(jMenu4);

        intSF.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout intSFLayout = new javax.swing.GroupLayout(intSF.getContentPane());
        intSF.getContentPane().setLayout(intSFLayout);
        intSFLayout.setHorizontalGroup(
            intSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intSFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(intSFLayout.createSequentialGroup()
                        .addGroup(intSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdROTINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdSTDINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdBUSINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        intSFLayout.setVerticalGroup(
            intSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intSFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(intSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(intSFLayout.createSequentialGroup()
                        .addComponent(cmdSTDINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdBUSINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(cmdROTINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        stdInfoSF.setTitle("Student Info");
        stdInfoSF.setMinimumSize(new java.awt.Dimension(497, 161));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("By bus no.");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("By Name");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("By Route No.");

        stdInfoSearch.setText("Click Here.");
        stdInfoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdInfoSearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Show All");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stdInfoSFLayout = new javax.swing.GroupLayout(stdInfoSF.getContentPane());
        stdInfoSF.getContentPane().setLayout(stdInfoSFLayout);
        stdInfoSFLayout.setHorizontalGroup(
            stdInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdInfoSFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(stdInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stdInfoSFLayout.createSequentialGroup()
                        .addComponent(stdInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(stdInfoSFLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton4)
                        .addGap(43, 43, 43))))
        );
        stdInfoSFLayout.setVerticalGroup(
            stdInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdInfoSFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(stdInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(stdInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        busInfoSF.setTitle("Student Info");
        busInfoSF.setMinimumSize(new java.awt.Dimension(497, 161));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("By bus no.");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("By Driver");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("By Route No.");

        busInfoSearch.setText("Click Here.");
        busInfoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busInfoSearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Show All");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busInfoSFLayout = new javax.swing.GroupLayout(busInfoSF.getContentPane());
        busInfoSF.getContentPane().setLayout(busInfoSFLayout);
        busInfoSFLayout.setHorizontalGroup(
            busInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busInfoSFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(busInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busInfoSFLayout.createSequentialGroup()
                        .addComponent(busInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(busInfoSFLayout.createSequentialGroup()
                        .addComponent(jRadioButton5)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButton6)
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton8)
                        .addGap(43, 43, 43))))
        );
        busInfoSFLayout.setVerticalGroup(
            busInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busInfoSFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(busInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(busInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rInfoSF.setTitle("Student Info");
        rInfoSF.setMinimumSize(new java.awt.Dimension(497, 161));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("By Route no.");

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("By Area1");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("By Area2");

        rInfoSearch.setText("Click Here.");
        rInfoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rInfoSearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("By Area3");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jButton2.setText("Show All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rInfoSFLayout = new javax.swing.GroupLayout(rInfoSF.getContentPane());
        rInfoSF.getContentPane().setLayout(rInfoSFLayout);
        rInfoSFLayout.setHorizontalGroup(
            rInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rInfoSFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(rInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rInfoSFLayout.createSequentialGroup()
                        .addComponent(rInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(rInfoSFLayout.createSequentialGroup()
                        .addComponent(jRadioButton9)
                        .addGap(37, 37, 37)
                        .addComponent(jRadioButton10)
                        .addGap(45, 45, 45)
                        .addComponent(jRadioButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton12)
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rInfoSFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(82, 82, 82))
        );
        rInfoSFLayout.setVerticalGroup(
            rInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rInfoSFLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(rInfoSFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(rInfoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Bootup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   final class Bus {
       String url,usr,pass,db;
       Connection conn;
        Statement stmt;
        ResultSet res;
        String query;
        DefaultTableModel table1;
       public Bus() {
           url = "jdbc:mysql://localhost:3306";
           usr = "root";
           pass = "";
           db = "bms";
            init();
            jTable1.setModel(new DefaultTableModel());
        table1 = (DefaultTableModel) jTable1.getModel();
       }
       void init() {
           try {
                //Loading the driver
            Class.forName("java.sql.DriverManager");
            //connecting to the database
            conn = DriverManager.getConnection(url,usr,pass);
            stmt = conn.createStatement();
            res=stmt.executeQuery("use " + db + ";");
            SOPL("Connected to Database server.");
            } catch(ClassNotFoundException | SQLException e) {
                SOPL(e.getMessage());
            }
       }
       boolean login(String usr, String pwd) {
           query="SELECT username from login where username='"+usr+"' and password='"+pwd+"'";
           String u1 = null;
           try {
               res=stmt.executeQuery(query);
               while(res.next()) {
                   u1 = res.getString(1);
                   SOPL(u1);
               }
               if(u1.equals(usr)) {
                   loggMenu.setText("Logged in as - " + usr);
                   return true;
               }
               else {
                   return false;
               }
           } catch(Exception e) {
               SOPL(e.getMessage());
           }
           return false;
       }
       void addStudent(String s_no,String r_no,String b_no,String s_name,String s_class,String s_stoppage) {
           query = "INSERT INTO `student` (`s_no`, `r_no`, `b_no`, `s_name`, `s_class`, `s_stoppage`) VALUES ('"+s_no+"', '"+r_no+"', '"+b_no+"', '"+s_name+"', '"+s_class+"', '"+s_stoppage+"')";
           SOPL(query);
           try {
               int r = stmt.executeUpdate(query);
               SOPL("addStudent() completed Successfully");
           } 
           catch( SQLException ex) {
           SEPL(ex.getMessage());
       }
       }
       void delStudent(String s_no) {
           query = "DELETE FROM student WHERE s_no='"+s_no+"';";
           SOPL(query);
           try {
               int r = stmt.executeUpdate(query);
               SOPL("delStudent() completed Successfully");
           } 
           catch( SQLException ex) {
           SEPL(ex.getMessage());
       }
       }
       void updStudent(String s_no) {
           try {
               int r = IP(JOptionPane.showInputDialog("Enter new Route id - "));
               int b = IP(JOptionPane.showInputDialog("Enter new Bus no - "));
               String sn = JOptionPane.showInputDialog("Enter new name - ");
               String sc = JOptionPane.showInputDialog("Enter new class - ");
               String ss = JOptionPane.showInputDialog("Enter new stoppage - ");
               query = " UPDATE student SET r_no="+r+", b_no="+b+", s_name='"+sn+"', s_class='"+sc+"', s_stoppage='"+ss+"' WHERE s_no="+s_no+";";
               int t = stmt.executeUpdate(query);
               SOPL("updStudent() completed Successfully");
           } catch(SQLException ex) {
               SEPL(ex.getMessage());
           }
       }
       void addBus(int b_no,int r_no,int b_students,String b_dname,String b_permit){
            query = "INSERT INTO bus VALUES ('"+b_no+"','"+r_no+"','"+b_dname+"','"+b_permit+"','"+b_students+"');";
            SOPL(query);
           try {
               int r = stmt.executeUpdate(query);
               SOPL("addBus() completed Successfully");
           } 
           catch( SQLException ex) {
           SEPL(ex.getMessage());
       }
       }
       void delBus(String b_no) {
           query = "DELETE FROM bus WHERE b_no='"+b_no+"';";
           SOPL(query);
           try {
               int r = stmt.executeUpdate(query);
               SOPL("delBus() completed Successfully");
           } 
           catch( SQLException ex) {
           SEPL(ex.getMessage());
       }
       }
       void updBus(String b_no) {
           try {
             int r = IP(JOptionPane.showInputDialog("Enter Route no - "));
             int bs = IP(JOptionPane.showInputDialog("Enter the no. of Students - "));
             String bd = JOptionPane.showInputDialog("Enter the driver name - ");
             String bp = JOptionPane.showInputDialog("Enter the Permist date(YYYY-MM-DD) - ");
             query = "UPDATE bus SET r_no="+r+",b_students="+bs+",b_dname='"+bd+"',b_permit="+bp+" WHERE b_no="+b_no+" ;";
             int t = stmt.executeUpdate(query);
             SOPL("updBus() completed successfully");
           } catch(SQLException ex) {
               SEPL(ex.getMessage());
           }
       }
       void addRoute(int r_no,String r_Ar1, String r_Ar2, String r_Ar3) {
           query = "INSERT INTO routes VALUES ('"+r_no+"','"+r_Ar1+"','"+r_Ar2+"','"+r_Ar3+"');";
            SOPL(query);
           try {
               int r = stmt.executeUpdate(query);
               SOPL("addRoute() completed Successfully");
           } 
           catch( SQLException ex) {
           SEPL(ex.getMessage());
       }
       }
       void delRoute(String r_no) {
           query = "DELETE FROM routes WHERE r_no='"+r_no+"';";
           SOPL(query);
           try {
               int r = stmt.executeUpdate(query);
               SOPL("delRoute() completed Successfully");
           } 
           catch( SQLException ex) {
           SEPL(ex.getMessage());
       }
       }
       void updRoute(String r_no) {
           try {
               String a1 = JOptionPane.showInputDialog("Enter Area1 - ");
               String a2 = JOptionPane.showInputDialog("Enter Area2 - ");
               String a3 = JOptionPane.showInputDialog("Enter Area3 - ");
               query = "UPDATE routes SET r_Ar1='"+a1+"', r_Ar2='"+a2+"', r_Ar3='"+a3+"' WHERE r_no="+r_no+" ;";
               int t = stmt.executeUpdate(query);
           } catch(SQLException ex) {
               SEPL(ex.getMessage());
           }
       }
       void stdInfo(String q) {
           try {
               res = stmt.executeQuery("desc student;");
            while(res.next()) {
                table1.addColumn(res.getString("Field"));
            }
               res=stmt.executeQuery(q);
               while(res.next()) {
                   table1.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
               }
               SOPL("stdInfo() completed.");
           } catch(SQLException ex) {
               SEPL(ex.getMessage());
           }
       }
       void busInfo(String q) {
            try {
               res = stmt.executeQuery("desc bus;");
            while(res.next()) {
                table1.addColumn(res.getString("Field"));
            }
               res=stmt.executeQuery(q);
               while(res.next()) {
                   table1.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
               }
               SOPL("busInfo() completed");
           } catch(SQLException ex) {
               SEPL(ex.getMessage());
           }
       }
       void rInfo(String q) {
           try {
               res = stmt.executeQuery("desc routes;");
            while(res.next()) {
                table1.addColumn(res.getString("Field"));
            }
               res=stmt.executeQuery(q);
               while(res.next()) {
                   table1.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
               }
               SOPL("rInfo() completed");
           } catch(SQLException ex) {
               SEPL(ex.getMessage());
           }
       }
   }
   Bus bms = new Bus();
    void SOPL(Object s) {
        System.out.println(s);
        jTextArea1.append("SOPL: "+s);
    }
    void SEPL (Object e) {
        System.err.println(e);
        jTextArea1.append("ERROR: "+e);
    }
    int IP(String s) {
        return Integer.parseInt(s);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SOPL("Event#1 Successfull");
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginSF.setVisible(true);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        SOPL("Event#2 Successfull");
        
        if(bms.login(usrTXT.getText(), pwdTXT.getText())) {
            SOPL("Login True");
        //loggMenu.setText("Logged in as - " + usrTXT.getText());
        loginSF.setVisible(false);
        intSF.setVisible(true);
        }
        else {
            SOPL("Login False");
        }
        
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void loggMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loggMenuActionPerformed
        // do nothng
    }//GEN-LAST:event_loggMenuActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        SOPL("Logout Event triggered");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void cmdSTDINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSTDINFOActionPerformed
        // TODO add your handling code here:
        stdInfoSF.setVisible(true);
    }//GEN-LAST:event_cmdSTDINFOActionPerformed

    private void stdInfoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdInfoSearchActionPerformed
        // TODO add your handling code here: 
        if(jRadioButton1.isSelected() || jRadioButton2.isSelected() || jRadioButton3.isSelected() || jRadioButton4.isSelected()) {
            //Do Nothing
        } else {
            SEPL("stdInfoSF - Search criteria not selected");
            JOptionPane.showMessageDialog(this, "No Criteria Selected!");
        }
        int ch;
        String q,s;
        if(jRadioButton1.isSelected()) {
            ch=1;
            s=JOptionPane.showInputDialog("Enter Bus no. - ");
            q="SELECT * FROM student WHERE b_no='"+s+"';";
        SOPL("stdInfo() function called");
        bms.stdInfo(q);
        } else if(jRadioButton2.isSelected()) {
            ch=2;
            s=JOptionPane.showInputDialog("Enter Name - ");
            q="SELECT * FROM student WHERE s_name='"+s+"';";
        SOPL("stdInfo() function called");
        bms.stdInfo(q);
        } else if(jRadioButton3.isSelected()) {
            ch=3;
            s=JOptionPane.showInputDialog("Enter Route no. - ");
            q="SELECT * FROM student WHERE r_no='"+s+"';";
        SOPL("stdInfo() function called");
        bms.stdInfo(q);
        } else if(jRadioButton4.isSelected()) {
            ch=4;
            q="SELECT * FROM student;";
        SOPL("stdInfo() function called");
        bms.stdInfo(q);
        }
    }//GEN-LAST:event_stdInfoSearchActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void busInfoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busInfoSearchActionPerformed
        // TODO add your handling code here:
        if(jRadioButton5.isSelected() || jRadioButton6.isSelected() || jRadioButton7.isSelected() || jRadioButton8.isSelected()) {
            //Do Nothing
        } else {
            SEPL("busInfoSF - Search criteria not selected");
            JOptionPane.showMessageDialog(this, "No Criteria Selected!");
        }
        int ch;
        String q,s;
        if(jRadioButton5.isSelected()) {
            ch=5;
            s=JOptionPane.showInputDialog("Enter Bus no-");
            q="SELECT * FROM bus WHERE b_no='"+s+"';";
            SOPL("busInfo() function called");
            bms.busInfo(q);
        } else if(jRadioButton6.isSelected()) {
            ch=6;
            s=JOptionPane.showInputDialog("Enter Driver name -");
            q="SELECT * FROM bus WHERE b_dname='"+s+"';";
            SOPL("busInfo() function called");
            bms.busInfo(q);
        } else if(jRadioButton7.isSelected()) {
            ch=7;
            s=JOptionPane.showInputDialog("Enter Route no-");
            q="SELECT * FROM bus WHERE r_no='"+s+"';";
            SOPL("busInfo() function called");
            bms.busInfo(q);
        } else if(jRadioButton8.isSelected()) {
            ch=8;
            q="SELECT * FROM bus;";
            SOPL("busInfo() function called");
            bms.busInfo(q);
        }
    }//GEN-LAST:event_busInfoSearchActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void cmdBUSINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBUSINFOActionPerformed
        // TODO add your handling code here:
        busInfoSF.setVisible(true);
    }//GEN-LAST:event_cmdBUSINFOActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void rInfoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rInfoSearchActionPerformed
        // TODO add your handling code here:
        if(jRadioButton9.isSelected() || jRadioButton10.isSelected() || jRadioButton11.isSelected() || jRadioButton12.isSelected()) {
            //Do Nothing
        } else {
            SEPL("rInfoSF - Search criteria not selected");
            JOptionPane.showMessageDialog(this, "No Criteria Selected!");
        }
        int ch;
        String q,s;
        if(jRadioButton9.isSelected()) {
            ch=9;
            s=JOptionPane.showInputDialog("Enter Route no. - ");
            q="SELECT * FROM routes WHERE r_no='"+s+"';";
            SOPL("rInfo() function called");
            bms.rInfo(q);
        } else if(jRadioButton10.isSelected()) {
            ch=10;
            s=JOptionPane.showInputDialog("Enter Area1 - ");
            q="SELECT * FROM routes WHERE r_Ar1='"+s+"';";
            SOPL("rInfo() function called");
            bms.rInfo(q);
            
        } else if(jRadioButton11.isSelected()) {
            ch=11;
            s=JOptionPane.showInputDialog("Enter Area2 - ");
            q="SELECT * FROM routes WHERE r_Ar2='"+s+"';";
            SOPL("rInfo() function called");
            bms.rInfo(q);
        } else if(jRadioButton12.isSelected()) {
            ch=12;
            s=JOptionPane.showInputDialog("Enter Area3 - ");
            q="SELECT * FROM routes WHERE r_Ar3='"+s+"';";
            SOPL("rInfo() function called");
            bms.rInfo(q);
        }
    }//GEN-LAST:event_rInfoSearchActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void cmdROTINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdROTINFOActionPerformed
        // TODO add your handling code here:
        rInfoSF.setVisible(true);
    }//GEN-LAST:event_cmdROTINFOActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String s_no,r_no,b_no,s_name,s_class,s_stoppage;
        s_no = JOptionPane.showInputDialog("Enter Student no - ");
        r_no = JOptionPane.showInputDialog("Enter Route no - ");
        b_no = JOptionPane.showInputDialog("Enter Bus no - ");
        s_name = JOptionPane.showInputDialog("Enter Student name - ");
        s_class = JOptionPane.showInputDialog("Enter Student's class - ");
        s_stoppage = JOptionPane.showInputDialog("Enter Student's Stoppage - ");
        if(s_no == null || r_no == null || b_no == null || s_name == null || s_class == null || s_stoppage == null) {
            SEPL("Error - 101");
            JOptionPane.showMessageDialog(this, "Error 101");
        }
        else {
            bms.addStudent(s_no, r_no, b_no, s_name, s_class, s_stoppage);
            SOPL("addStudent() function called");
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String s_no = JOptionPane.showInputDialog("Enter the s_no - ");
        bms.delStudent(s_no);
        SOPL("delStudent() function called");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String s_no = JOptionPane.showInputDialog("Enter the s_no of the student whom you want to edit - ");
        bms.updStudent(s_no);
        SOPL("updStudent() function called");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        int b_no,r_no,b_students;
        String b_dname,b_permit;
        r_no = IP(JOptionPane.showInputDialog("Enter Route no - "));
        b_no = IP(JOptionPane.showInputDialog("Enter Bus no - "));
        b_students = IP(JOptionPane.showInputDialog("Enter the no. of Students - "));
        b_dname = JOptionPane.showInputDialog("Enter the driver name - ");
        b_permit = JOptionPane.showInputDialog("Enter the Permist date(YYYY-MM-DD) - ");
        bms.addBus(b_no, r_no, b_students, b_dname, b_permit);
        SOPL("addBus() function called");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        String b_no = JOptionPane.showInputDialog("Enter the b_no - ");
        bms.delBus(b_no);
        SOPL("delBus() function called");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        String b_no = JOptionPane.showInputDialog("Enter the b_no of the bus whom you want to edit - ");
        bms.updBus(b_no);
        SOPL("updBus() function called");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        int r_no = IP(JOptionPane.showInputDialog("Enter new Route no - "));
        String r_Ar1=JOptionPane.showInputDialog("Enter Area1 - ");
        String r_Ar2=JOptionPane.showInputDialog("Enter Area2 - ");
        String r_Ar3=JOptionPane.showInputDialog("Enter Area3 - ");
        bms.addRoute(r_no, r_Ar1, r_Ar2, r_Ar3);
        SOPL("addRoute() function called");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        String r_no = JOptionPane.showInputDialog("Enter the r_no - ");
        bms.delRoute(r_no);
        SOPL("delRoute() function called");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String q;
            q="SELECT * FROM routes;";
            SOPL("rInfo() function called");
            bms.rInfo(q);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame busInfoSF;
    private javax.swing.JButton busInfoSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdBUSINFO;
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdROTINFO;
    private javax.swing.JButton cmdSTDINFO;
    private javax.swing.JFrame intSF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem loggMenu;
    private javax.swing.JFrame loginSF;
    private javax.swing.JPasswordField pwdTXT;
    private javax.swing.JFrame rInfoSF;
    private javax.swing.JButton rInfoSearch;
    private javax.swing.JFrame stdInfoSF;
    private javax.swing.JButton stdInfoSearch;
    private javax.swing.JTextField usrTXT;
    // End of variables declaration//GEN-END:variables
}
